config/routes.rb
Blog::Application.routes.draw do

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :draft_posts, only: [ :index, :show ]
  resources :posts
  resources :sections
  resources :photos

  resources :pages

  root :to => 'posts#index'

end

app/controllers/draft_posts_controller.rb
class DraftPostsController < ApplicationController
  # GET /draft_posts
  # GET /draft_posts.json
  def index
    @draft_posts = Post.drafts.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @draft_posts }
    end
  end

  # GET /draft_posts/1
  # GET /draft_posts/1.json
  def show
    @draft_post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @draft_post }
    end
  end

end

app/helpers/draft_posts_helper.rb
module DraftPostsHelper
end

app/views/draft_posts/index.html.haml
%h1 Listing draft_posts
%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th
  - @draft_posts.each do |post|
    %tr
      %td= post.title
      %td= post.body
      %td= link_to 'Show', draft_post_path(post)
      - if admin_logged_in?
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete
- if admin_logged_in?
  %br/
  = link_to 'New Post', new_post_path

app/views/draft_posts/show.html.haml
%article
  %header
    %h3= @draft_post.title
  %section
    :textile
      #{@draft_post.body}
%nav
  - if admin_logged_in?
    = link_to 'Edit', edit_post_path(@draft_post)
    |
  = link_to 'Back', draft_posts_path