config/routes.rb
Blog::Application.routes.draw do

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :draft_posts, only: [ :index, :show ]
  resources :posts
  resources :sections
  resources :photos

  resources :pages

  root :to => 'posts#index'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :body

  belongs_to :comment
  belongs_to :admin

  # Validations
  validates :body,               presence: true,
                                           length: { within: 3..1024 }
  validates :admin_id,        presence: true
  validates :comment_id,   presence: true

  # Scopes
  default_scope order('created_at DESC') # test

end




# == Schema Information
#
# Table name: replies
#
#  id         :integer         not null, primary key
#  body       :text
#  comment_id :integer
#  created_at :datetime
#  updated_at :datetime
#  admin_id   :integer
#

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @reply = Reply.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply])

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.haml
= form_for @reply do |f|
  -if @reply.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reply.errors.count, "error")} prohibited this reply from being saved:"
      %ul
        - @reply.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_field :body
  .actions
    = f.submit 'Save'

app/views/replies/edit.html.haml
%h1 Editing reply

= render 'form'

= link_to 'Show', @reply
\|
= link_to 'Back', replies_path

app/views/replies/index.html.haml
%h1 Listing replies

%table
  %tr
    %th Body
    %th
    %th
    %th

  - @replies.each do |reply|
    %tr
      %td= reply.body
      %td= link_to 'Show', reply
      %td= link_to 'Edit', edit_reply_path(reply)
      %td= link_to 'Destroy', reply, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Reply', new_reply_path

app/views/replies/new.html.haml
%h1 New reply

= render 'form'

= link_to 'Back', replies_path

app/views/replies/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @reply.body

= link_to 'Edit', edit_reply_path(@reply)
\|
= link_to 'Back', replies_path