config/routes.rb
Blog::Application.routes.draw do

  match 'admin/edit' => 'admins#edit', :as => :edit_current_admin
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions, only: [ :new, :create, :destroy]
  resources :admins, only: [ :edit, :update ]

  resources :replies
  resources :comments

  resources :draft_posts, only: [ :index, :show ]
  resources :posts
  resources :sections
  resources :photos

  resources :pages

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :email, :url, :body

  belongs_to :post
  has_many  :replies, dependent: :destroy

  # States and Transitions with state_machine gem
  state_machine initial: :unapproved do
    event :approved do
      transition unapproved: :approved
    end
  end

  # Validations
  # email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  name_regex = /[a-zA-Z0-9_ ]/i
  # url_regex = \b((ftp|https?)://[-\w]+(\.\w[-\w]*)+ | (?i: [a-z0-9] (?:[-a-z0-9]*[a-z0-9])? \. )+(?-i: com\b | edu\b | biz\b | gov\b | in(?:t|fo)\b | mil\b | net\b | org\b | [a-z][a-z]\b ))( : \d+ )?)/[^.!,?;<>()\[\]{}\s\x7F-\xFF]*(?:[.!,?]+  [^.!,?;<>()\[\]{}\s\x7F-\xFF]+)*)?

  validates :name,           presence: true,
                                        length: { within: 3..60 },
                                        format: name_regex
  validates :email,           presence: true,
                                        length: { within: 5..120 },
                                        format: email_regex
  validates :url,                length: { within: 9..254, allow_blank: true }
  validates :body,            presence: true,
                                        length: { within: 3..1024 }
  validates :post_id,        presence: true#, on: :create

  # Scopes
  default_scope order('created_at DESC') # test
  scope :unapproved, where(state: 'unapproved')
  scope :approved, where(state: 'approved')


end


# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  url        :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  state      :string(255)
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for @comment do |f|
  = f.error_messages

  %p.field
    = f.label :name
    %br/
    = f.text_field :name
  %p.field
    = f.label :email
    (your email will not be shared)
    %br/
    = f.text_field :email
  %p.field
    = f.label :url
    %br/
    = f.text_field :url
  %p.field
    = f.label :body
    (supports textile formatting)
    %br/
    = f.text_area :body
  %p.actions
    = f.submit 'Save'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%article
  %header
    %h3= link_to @comment.name, @comment.url
  %section
    :textile
      #{@comment.body}
%nav
  - if admin_logged_in?
    = link_to 'Edit', edit_comment_path(@comment)
    |
  = link_to 'Back', comments_path